#include "cfd/mesh/bc.hpp"

#include <mpi.h>

#include <cstdio>
#include <unordered_map>

#include "cfd/mesh/cgns_reader.hpp"
#include "cfd/mesh/faces.hpp"
#include "cfd/mpi/log.hpp"
#include "cfd/mpi/mpi_util.hpp"

namespace {

struct SurfDist {  // BC element redistributed to the key owner
    FaceKey key;
    int32_t patch;
};
struct MatchReq {  // face matching request
    FaceKey key;
    int32_t face_local;
};
struct MatchResp {
    int32_t face_local;
    int32_t patch;
};

}  // namespace

bool match_boundaries(RawMesh& m, MeshPart& mp, std::vector<FaceRec>& faces) {
    const int nprocs = m.nprocs;

    // --- BC elements -> key owners (block distribution of nodes) ---
    std::vector<std::vector<SurfDist>> sd_out(nprocs);
    for (const SurfElem& se : m.surf_elems)
        sd_out[block_owner(se.key.v[0], m.node_displ)].push_back({se.key, se.patch});
    auto sd_in = alltoall_vec(sd_out);
    sd_out.clear();
    std::unordered_map<FaceKey, int32_t, FaceKeyHash> bc_map;
    bc_map.reserve(sd_in.size() * 2 + 16);
    long long dup = 0;
    for (auto& buf : sd_in)
        for (const SurfDist& s : buf) {
            auto it = bc_map.find(s.key);
            if (it == bc_map.end())
                bc_map[s.key] = s.patch;
            else if (it->second != s.patch)
                ++dup;
        }
    sd_in.clear();

    // --- Boundary-face requests ---
    std::vector<std::vector<MatchReq>> req(nprocs);
    for (int i = 0; i < mp.n_faces; ++i)
        if (mp.face_neigh[i] < 0)
            req[block_owner(faces[i].key.v[0], m.node_displ)].push_back({faces[i].key, i});
    auto rq_in = alltoall_vec(req);
    req.clear();

    std::vector<std::vector<MatchResp>> resp(nprocs);
    long long unmatched_here = 0;
    std::unordered_map<FaceKey, int32_t, FaceKeyHash> used_keys;
    for (int p = 0; p < nprocs; ++p) {
        for (const MatchReq& r : rq_in[p]) {
            const auto it = bc_map.find(r.key);
            if (it == bc_map.end())
                ++unmatched_here;
            else
                used_keys[r.key] = it->second;
            resp[p].push_back({r.face_local, it != bc_map.end() ? it->second : -1});
        }
    }
    rq_in.clear();
    auto rp_in = alltoall_vec(resp);
    resp.clear();
    for (auto& buf : rp_in)
        for (const MatchResp& r : buf) mp.face_patch[r.face_local] = r.patch;
    rp_in.clear();

    // --- Unused BC elements (key present, no such face) ---
    long long unused_bc = 0;
    for (const auto& kv : bc_map)
        if (!used_keys.count(kv.first)) ++unused_bc;

    const long long unmatched_g = ll_sum(unmatched_here);
    const long long unused_g = ll_sum(unused_bc);
    const long long dup_g = ll_sum(dup);
    if (dup_g > 0) log_rank("BC keys with conflicting patches (global): %lld", dup_g);

    // --- patch_faces: per-patch counting + lexicographic order ---
    const int np = static_cast<int>(mp.patches.size());
    std::vector<int> cnt(np + 1, 0);
    for (int i = 0; i < mp.n_faces; ++i)
        if (mp.face_patch[i] >= 0) ++cnt[mp.face_patch[i]];
    mp.patch_face_offsets.assign(np + 1, 0);
    for (int p = 0; p < np; ++p) mp.patch_face_offsets[p + 1] = mp.patch_face_offsets[p] + cnt[p];
    mp.patch_faces.assign(mp.patch_face_offsets[np], -1);
    {
        std::vector<int> pos(mp.patch_face_offsets.begin(), mp.patch_face_offsets.end() - 1);
        for (int i = 0; i < mp.n_faces; ++i)
            if (mp.face_patch[i] >= 0) mp.patch_faces[pos[mp.face_patch[i]]++] = i;
    }

    if (unmatched_g > 0) log_warn_rank("boundary faces without a BC (global): %lld", unmatched_g);
    if (unused_g > 0)
        log_warn_rank("CGNS BC elements not matched to any face (global): %lld", unused_g);
    return unmatched_g == 0 && unused_g == 0;
}

void write_bc_config(const MeshPart& mp, const std::string& path) {
    // Global per-patch face counts (allreduce) so the file shows totals,
    // not some single rank's share. Must be called by ALL ranks; only
    // rank 0 writes the file.
    const int np = static_cast<int>(mp.patches.size());
    std::vector<long long> faces_per_patch(np, 0);
    for (int p = 0; p < np; ++p)
        faces_per_patch[p] = mp.patch_face_offsets[p + 1] - mp.patch_face_offsets[p];
    MPI_Allreduce(MPI_IN_PLACE, faces_per_patch.data(), np, MPI_LONG_LONG_INT, MPI_SUM,
                  MPI_COMM_WORLD);

    int rank = 0;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    if (rank != 0) return;

    FILE* f = std::fopen(path.c_str(), "w");
    if (!f) {
        log_warn_rank("could not open %s for writing the BC file", path.c_str());
        return;
    }
    std::fprintf(f,
                 "# Boundary condition file. Auto-generated by the preprocessor.\n"
                 "# Fill in 'type' and the parameters. Per-patch local face indices "
                 "live in the HDF5 file (patches/face_idx + patchfaces_off).\n"
                 "# Allowed types: inlet_supersonic, inlet_subsonic, "
                 "outlet_supersonic, outlet_subsonic,\n"
                 "#                  symmetry, wall_slip, wall_noslip\n\n");
    for (int p = 0; p < np; ++p) {
        std::fprintf(f, "[patch.%d]\n", p);
        std::fprintf(f, "id = %d\n", p);
        std::fprintf(f, "name = \"%s\"\n", mp.patches[p].name.c_str());
        std::fprintf(f, "cgns_type = \"%s\"\n", mp.patches[p].cgns_type.c_str());
        std::fprintf(f, "type = \"userdefined\"\n");
        std::fprintf(f, "n_faces = %lld\n", faces_per_patch[p]);
        std::fprintf(f, "\n[patch.%d.params]\n", p);
        std::fprintf(f,
                     "# Parameter examples per type (fill in the ones you need):\n"
                     "# inlet_supersonic: Mach, alpha_deg, beta_deg, p_static, T_static\n"
                     "# inlet_subsonic:  Mach, alpha_deg, p_total, T_total\n"
                     "# outlet_*:        p_static (or full p, u, T)\n"
                     "# symmetry, wall_slip, wall_noslip: no parameters\n\n");
    }
    std::fclose(f);
}
