#include "cfd/mesh/bc_config.hpp"

#include <fstream>
#include <string>
#include <vector>
#include <cstdint>

#include "cfd/mpi/log.hpp"

namespace cfd::mesh {

namespace {

// Maps CGNS BC type to a sensible default solver BC type. Only conditions
// implemented by the solver are used as defaults; everything else falls back
// to the USER_DEFINED placeholder, which the solver config parser rejects
// with a clear message until the user picks a real type.
std::string guess_default_solver_bc(const std::string& cgns_type) {
    if (cgns_type == "BCWall" || cgns_type == "BCWallInviscid") {
        return "SLIP_WALL";
    }
    if (cgns_type == "BCSymmetryPlane") {
        return "SYMMETRY";
    }
    if (cgns_type == "BCInflow" || cgns_type == "BCInflowSubsonic" ||
        cgns_type == "BCInflowSupersonic") {
        return "SUPERSONIC_INLET";
    }
    if (cgns_type == "BCOutflow" || cgns_type == "BCOutflowSubsonic" ||
        cgns_type == "BCOutflowSupersonic") {
        return "SUPERSONIC_OUTLET";
    }
    if (cgns_type == "BCFarfield") {
        return "FARFIELD";
    }
    return "USER_DEFINED";
}

// Parameter block emitted right below the type of one patch. Keys must match
// the strict solver parser exactly (cfd/solver/config.hpp).
void write_param_block(std::ofstream& out, const std::string& type) {
    if (type == "SUPERSONIC_INLET") {
        out << "p         = 101325.0        # Static pressure [Pa]\n";
        out << "t         = 300.0           # Static temperature [K]\n";
        out << "mach      = 2.0             # Inlet Mach number [-]\n";
        out << "direction = [1.0, 0.0, 0.0] # Flow direction (any non-zero length)\n";
    } else if (type == "FARFIELD") {
        out << "mach_inf = 2.0      # Freestream Mach number [-]\n";
        out << "p_inf    = 101325.0 # Freestream static pressure [Pa]\n";
        out << "t_inf    = 300.0    # Freestream static temperature [K]\n";
        out << "alpha    = 0.0      # Angle of attack [deg] (optional)\n";
        out << "beta     = 0.0      # Sideslip angle [deg] (optional)\n";
    } else if (type == "USER_DEFINED") {
        out << "# [Pick a type above, then uncomment its parameters]\n";
        out << "# p         = 101325.0        # SUPERSONIC_INLET: static pressure [Pa]\n";
        out << "# t         = 300.0           # SUPERSONIC_INLET: static temperature [K]\n";
        out << "# mach      = 2.0             # SUPERSONIC_INLET: Mach number [-]\n";
        out << "# direction = [1.0, 0.0, 0.0] # SUPERSONIC_INLET: flow direction\n";
        out << "# mach_inf  = 2.0             # FARFIELD: freestream Mach number\n";
        out << "# p_inf     = 101325.0        # FARFIELD: static pressure [Pa]\n";
        out << "# t_inf     = 300.0           # FARFIELD: static temperature [K]\n";
        out << "# alpha     = 0.0             # FARFIELD: angle of attack [deg]\n";
        out << "# beta      = 0.0             # FARFIELD: sideslip angle [deg]\n";
    } else {
        out << "# (no parameters for this BC type)\n";
    }
    out << "\n";
}

} // anonymous namespace

void generate_bc_template_config(const MeshPart& mp, const std::string& output_filepath) {
    const int rank = mp.rank;
    const std::size_t n_patches = mp.patches.size();

    // 1. Gather global face counts per patch across all ranks
    std::vector<std::uint64_t> local_patch_faces(n_patches, 0);
    for (std::size_t p = 0; p < n_patches; ++p) {
        local_patch_faces[p] = static_cast<std::uint64_t>(mp.patch_face_offsets[p + 1] - mp.patch_face_offsets[p]);
    }

    std::vector<std::uint64_t> global_patch_faces(n_patches, 0);
    if (n_patches > 0) {
        MPI_Reduce(local_patch_faces.data(), global_patch_faces.data(),
                   static_cast<int>(n_patches), MPI_UINT64_T, MPI_SUM, 0, MPI_COMM_WORLD);
    }
    
    if (rank != 0) {
        return;
    }

    // 2. Write TOML-style configuration template on Rank 0
    std::ofstream out(output_filepath);
    if (!out.is_open()) {
        mpi::log_stat("WARNING: Failed to open BC config output file: %s", output_filepath.c_str());
        return;
    }

    out << "# =============================================================================\n";
    out << "# Solver Boundary Conditions Configuration\n";
    out << "# Auto-generated by Mesh Pipeline\n";
    out << "#\n";
    out << "# Total Boundary Patches: " << n_patches << "\n";
    out << "# Total Global Boundary Faces: " << mp.n_bfaces_g << "\n";
    out << "#\n";
    out << "# Available BC Types (implemented):\n";
    out << "#   - SLIP_WALL          (Inviscid slip wall; no parameters)\n";
    out << "#   - SYMMETRY           (Planar symmetry; no parameters)\n";
    out << "#   - SUPERSONIC_INLET   (p [Pa], t [K], mach, direction [x, y, z])\n";
    out << "#   - SUPERSONIC_OUTLET  (Supersonic outflow extrapolation; no parameters)\n";
    out << "#   - FARFIELD           (mach_inf, p_inf [Pa], t_inf [K], alpha [deg], beta [deg])\n";
    out << "#\n";
    out << "# Planned BC Types (not yet implemented by the solver):\n";
    out << "#   - SUBSONIC_INLET     (p0 [Pa], t0 [K], direction)\n";
    out << "#   - PRESSURE_OUTLET    (p_back [Pa])\n";
    out << "#   - WALL_ADIABATIC     (No-slip viscous adiabatic wall)\n";
    out << "#   - WALL_ISOTHERMAL    (t_wall [K])\n";
    out << "# =============================================================================\n\n";

    for (std::size_t p = 0; p < n_patches; ++p) {
        const auto& patch = mp.patches[p];
        const std::string default_bc = guess_default_solver_bc(patch.cgns_type);

        out << "[[boundary_condition]]\n";
        out << "patch_id          = " << p << "\n";
        out << "name              = \"" << patch.name << "\"\n";
        out << "cgns_type         = \"" << patch.cgns_type << "\"\n";
        out << "global_face_count = " << global_patch_faces[p] << "\n";
        out << "type              = \"" << default_bc << "\"\n\n";

        write_param_block(out, default_bc);
        out << "# -----------------------------------------------------------------------------\n\n";
    }

    out.close();
    mpi::log_stat("INFO: Boundary conditions template generated at: %s", output_filepath.c_str());
}

} // namespace cfd::mesh
