#include "cfd/mesh/bc_config.hpp"

#include <fstream>
#include <string>
#include <vector>
#include <cstdint>

#include "cfd/mpi/log.hpp"
 
namespace cfd::mesh {

namespace {

// Maps CGNS BC type to a sensible default solver BC template
std::string guess_default_solver_bc(const std::string& cgns_type) {
    if (cgns_type == "BCWall" || cgns_type == "BCWallViscous") {
        return "WALL_ADIABATIC";
    }
    if (cgns_type == "BCWallInviscid" || cgns_type == "BCSymmetryPlane") {
        return "SYMMETRY";
    }
    if (cgns_type == "BCInflow" || cgns_type == "BCInflowSubsonic" || cgns_type == "BCInflowSupersonic") {
        return "INLET_TOTAL_TP";
    }
    if (cgns_type == "BCOutflow" || cgns_type == "BCOutflowSubsonic") {
        return "OUTLET_BACK_PRESSURE";
    }
    if (cgns_type == "BCFarfield") {
        return "FARFIELD";
    }
    return "USER_DEFINED"; // Fallback for UserDefined / Unknown
}

} // anonymous namespace

void generate_bc_template_config(const MeshPart& mp, const std::string& output_filepath) {
    const int rank = mp.rank;
    const std::size_t n_patches = mp.patches.size();

    // 1. Gather global face counts per patch across all ranks
    std::vector<std::uint64_t> local_patch_faces(n_patches, 0);
    for (std::size_t p = 0; p < n_patches; ++p) {
        local_patch_faces[p] = static_cast<std::uint64_t>(mp.patch_face_offsets[p + 1] - mp.patch_face_offsets[p]);
    }

    std::vector<std::uint64_t> global_patch_faces(n_patches, 0);
    MPI_Reduce(local_patch_faces.data(), global_patch_faces.data(), 
               static_cast<int>(n_patches), MPI_INT64_T, MPI_SUM, 0, MPI_COMM_WORLD);

    if (rank != 0) {
        return;
    }

    // 2. Write TOML-style configuration template on Rank 0
    std::ofstream out(output_filepath);
    if (!out.is_open()) {
        mpi::log_stat("WARNING: Failed to open BC config output file: %s", output_filepath.c_str());
        return;
    }

    out << "# =============================================================================\n";
    out << "# Solver Boundary Conditions Configuration Template\n";
    out << "# Auto-generated by Mesh Pipeline\n";
    out << "#\n";
    out << "# Total Boundary Patches: " << n_patches << "\n";
    out << "# Total Global Boundary Faces: " << mp.n_bfaces_g << "\n";
    out << "#\n";
    out << "# Available BC Types:\n";
    out << "#   - INLET_TOTAL_TP       (Parameters: p0 [Pa], T0 [K], direction [x, y, z])\n";
    out << "#   - INLET_SUPERSONIC     (Parameters: p [Pa], T [K], M, direction [x, y, z])\n";
    out << "#   - OUTLET_BACK_PRESSURE (Parameters: p_back [Pa])\n";
    out << "#   - OUTLET_SUPERSONIC    (No parameters needed - full extrapolation)\n";
    out << "#   - WALL_ADIABATIC       (No-slip viscous adiabatic wall)\n";
    out << "#   - WALL_ISOTHERMAL      (Parameters: T_wall [K])\n";
    out << "#   - SYMMETRY             (Inviscid slip wall / planar symmetry)\n";
    out << "#   - FARFIELD             (Parameters: M_inf, p_inf [Pa], T_inf [K], alpha [deg], beta [deg])\n";
    out << "# =============================================================================\n\n";

    for (std::size_t p = 0; p < n_patches; ++p) {
        const auto& patch = mp.patches[p];
        const std::string default_bc = guess_default_solver_bc(patch.cgns_type);

        out << "[[boundary_condition]]\n";
        out << "patch_id          = " << p << "\n";
        out << "name              = \"" << patch.name << "\"\n";
        out << "cgns_type         = \"" << patch.cgns_type << "\"\n";
        out << "global_face_count = " << global_patch_faces[p] << "\n";
        out << "type              = \"" << default_bc << "\"\n\n";

        out << "# [Parameters Template - uncomment and edit required fields]\n";
        out << "# p0         = 101325.0    # Total pressure [Pa]\n";
        out << "# T0         = 300.0       # Total temperature [K]\n";
        out << "# p_back     = 101325.0    # Static back pressure [Pa]\n";
        out << "# T_wall     = 300.0       # Isothermal wall temperature [K]\n";
        out << "# direction  = [1.0, 0.0, 0.0] # Normalized flow direction vector\n";
        out << "# mach_inf   = 0.8         # Farfield Mach number\n";
        out << "# alpha      = 0.0         # Angle of attack [deg]\n";
        out << "# beta       = 0.0         # Sideslip angle [deg]\n\n";
        out << "# -----------------------------------------------------------------------------\n\n";
    }

    out.close();
    mpi::log_stat("INFO: Boundary conditions template generated at: %s", output_filepath.c_str());
}

} // namespace cfd::mesh